project:
  type: book

book:
  title: "Epistem-X Technical Documentation"
  author: "IIASA"
  date: "18/09/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - module01.qmd
    - placeholders/module02_placeholder.qmd
    - module03.qmd
    - module04.qmd
    - placeholders/module05_placeholder.qmd
    - module06.qmd
    - module07.qmd
    - placeholders/module08_placeholder.qmd
    - summary.qmd
    - references.qmd
  sidebar:
    logo: images/epistem_logo_color.png
    search: true
    tools:
      - icon: globe
        href: https://epistem.io/
  
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true
    number-depth: 5
    

  pdf:
    documentclass: scrreprt

editor: visual

