project:
  type: book

book:
  title: "Epistem-X Technical Documentation"
  author: "IIASA"
  date: "17/09/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - module01.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

